version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: chater-dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
